export * from './view';
export * from './text';
export * from './swiper';
export * from './scrollView';
export * from './loading';
export * from './tabs';
export * from './popup';
export * from './numStep';
export * from './iconMobile';
export * from './radio'
export * from './checkbox'
export * from './wrapLoading'
